/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as BracketRouteImport } from './routes/bracket'
import { Route as GameRouteImport } from './routes/game'
import { Route as GkReportRouteImport } from './routes/gk-report'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as QuartersRouteImport } from './routes/quarters'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupGameInfoRouteImport } from './routes/setup.game-info'
import { Route as SetupMiscRouteImport } from './routes/setup.misc'
import { Route as SetupPlayersRouteImport } from './routes/setup.players'
import { Route as SetupSystemCheckRouteImport } from './routes/setup.system-check'
import { Route as SetupTeamsRouteImport } from './routes/setup.teams'
import { Route as PlayersTeamNamePlayerNoRouteImport } from './routes/players.$teamName.$playerNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketRoute = BracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GkReportRoute = GkReportRouteImport.update({
  id: '/gk-report',
  path: '/gk-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartersRoute = QuartersRouteImport.update({
  id: '/quarters',
  path: '/quarters',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupGameInfoRoute = SetupGameInfoRouteImport.update({
  id: '/game-info',
  path: '/game-info',
  getParentRoute: () => SetupRoute,
} as any)
const SetupMiscRoute = SetupMiscRouteImport.update({
  id: '/misc',
  path: '/misc',
  getParentRoute: () => SetupRoute,
} as any)
const SetupPlayersRoute = SetupPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => SetupRoute,
} as any)
const SetupSystemCheckRoute = SetupSystemCheckRouteImport.update({
  id: '/system-check',
  path: '/system-check',
  getParentRoute: () => SetupRoute,
} as any)
const SetupTeamsRoute = SetupTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => SetupRoute,
} as any)
const PlayersTeamNamePlayerNoRoute = PlayersTeamNamePlayerNoRouteImport.update({
  id: '/$teamName/$playerNo',
  path: '/$teamName/$playerNo',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/bracket': typeof BracketRoute
  '/game': typeof GameRoute
  '/gk-report': typeof GkReportRoute
  '/home': typeof HomeRoute
  '/players': typeof PlayersRouteWithChildren
  '/quarters': typeof QuartersRoute
  '/reports': typeof ReportsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/season': typeof SeasonRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/setup/game-info': typeof SetupGameInfoRoute
  '/setup/misc': typeof SetupMiscRoute
  '/setup/players': typeof SetupPlayersRoute
  '/setup/system-check': typeof SetupSystemCheckRoute
  '/setup/teams': typeof SetupTeamsRoute
  '/players/': typeof PlayersIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/players/$teamName/$playerNo': typeof PlayersTeamNamePlayerNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/bracket': typeof BracketRoute
  '/game': typeof GameRoute
  '/gk-report': typeof GkReportRoute
  '/home': typeof HomeRoute
  '/quarters': typeof QuartersRoute
  '/reports': typeof ReportsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/season': typeof SeasonRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/setup/game-info': typeof SetupGameInfoRoute
  '/setup/misc': typeof SetupMiscRoute
  '/setup/players': typeof SetupPlayersRoute
  '/setup/system-check': typeof SetupSystemCheckRoute
  '/setup/teams': typeof SetupTeamsRoute
  '/players': typeof PlayersIndexRoute
  '/setup': typeof SetupIndexRoute
  '/players/$teamName/$playerNo': typeof PlayersTeamNamePlayerNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/bracket': typeof BracketRoute
  '/game': typeof GameRoute
  '/gk-report': typeof GkReportRoute
  '/home': typeof HomeRoute
  '/players': typeof PlayersRouteWithChildren
  '/quarters': typeof QuartersRoute
  '/reports': typeof ReportsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/season': typeof SeasonRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/setup/game-info': typeof SetupGameInfoRoute
  '/setup/misc': typeof SetupMiscRoute
  '/setup/players': typeof SetupPlayersRoute
  '/setup/system-check': typeof SetupSystemCheckRoute
  '/setup/teams': typeof SetupTeamsRoute
  '/players/': typeof PlayersIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/players/$teamName/$playerNo': typeof PlayersTeamNamePlayerNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/bracket'
    | '/game'
    | '/gk-report'
    | '/home'
    | '/players'
    | '/quarters'
    | '/reports'
    | '/scoreboard'
    | '/season'
    | '/settings'
    | '/setup'
    | '/standings'
    | '/stats'
    | '/unlock'
    | '/welcome'
    | '/setup/game-info'
    | '/setup/misc'
    | '/setup/players'
    | '/setup/system-check'
    | '/setup/teams'
    | '/players/'
    | '/setup/'
    | '/players/$teamName/$playerNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/bracket'
    | '/game'
    | '/gk-report'
    | '/home'
    | '/quarters'
    | '/reports'
    | '/scoreboard'
    | '/season'
    | '/settings'
    | '/standings'
    | '/stats'
    | '/unlock'
    | '/welcome'
    | '/setup/game-info'
    | '/setup/misc'
    | '/setup/players'
    | '/setup/system-check'
    | '/setup/teams'
    | '/players'
    | '/setup'
    | '/players/$teamName/$playerNo'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/bracket'
    | '/game'
    | '/gk-report'
    | '/home'
    | '/players'
    | '/quarters'
    | '/reports'
    | '/scoreboard'
    | '/season'
    | '/settings'
    | '/setup'
    | '/standings'
    | '/stats'
    | '/unlock'
    | '/welcome'
    | '/setup/game-info'
    | '/setup/misc'
    | '/setup/players'
    | '/setup/system-check'
    | '/setup/teams'
    | '/players/'
    | '/setup/'
    | '/players/$teamName/$playerNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  BracketRoute: typeof BracketRoute
  GameRoute: typeof GameRoute
  GkReportRoute: typeof GkReportRoute
  HomeRoute: typeof HomeRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  QuartersRoute: typeof QuartersRoute
  ReportsRoute: typeof ReportsRoute
  ScoreboardRoute: typeof ScoreboardRoute
  SeasonRoute: typeof SeasonRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
  StandingsRoute: typeof StandingsRoute
  StatsRoute: typeof StatsRoute
  UnlockRoute: typeof UnlockRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket': {
      id: '/bracket'
      path: '/bracket'
      fullPath: '/bracket'
      preLoaderRoute: typeof BracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gk-report': {
      id: '/gk-report'
      path: '/gk-report'
      fullPath: '/gk-report'
      preLoaderRoute: typeof GkReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarters': {
      id: '/quarters'
      path: '/quarters'
      fullPath: '/quarters'
      preLoaderRoute: typeof QuartersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/game-info': {
      id: '/setup/game-info'
      path: '/game-info'
      fullPath: '/setup/game-info'
      preLoaderRoute: typeof SetupGameInfoRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/misc': {
      id: '/setup/misc'
      path: '/misc'
      fullPath: '/setup/misc'
      preLoaderRoute: typeof SetupMiscRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/players': {
      id: '/setup/players'
      path: '/players'
      fullPath: '/setup/players'
      preLoaderRoute: typeof SetupPlayersRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/system-check': {
      id: '/setup/system-check'
      path: '/system-check'
      fullPath: '/setup/system-check'
      preLoaderRoute: typeof SetupSystemCheckRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/teams': {
      id: '/setup/teams'
      path: '/teams'
      fullPath: '/setup/teams'
      preLoaderRoute: typeof SetupTeamsRouteImport
      parentRoute: typeof SetupRoute
    }
    '/players/$teamName/$playerNo': {
      id: '/players/$teamName/$playerNo'
      path: '/$teamName/$playerNo'
      fullPath: '/players/$teamName/$playerNo'
      preLoaderRoute: typeof PlayersTeamNamePlayerNoRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersIndexRoute: typeof PlayersIndexRoute
  PlayersTeamNamePlayerNoRoute: typeof PlayersTeamNamePlayerNoRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersIndexRoute: PlayersIndexRoute,
  PlayersTeamNamePlayerNoRoute: PlayersTeamNamePlayerNoRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface SetupRouteChildren {
  SetupGameInfoRoute: typeof SetupGameInfoRoute
  SetupMiscRoute: typeof SetupMiscRoute
  SetupPlayersRoute: typeof SetupPlayersRoute
  SetupSystemCheckRoute: typeof SetupSystemCheckRoute
  SetupTeamsRoute: typeof SetupTeamsRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupGameInfoRoute: SetupGameInfoRoute,
  SetupMiscRoute: SetupMiscRoute,
  SetupPlayersRoute: SetupPlayersRoute,
  SetupSystemCheckRoute: SetupSystemCheckRoute,
  SetupTeamsRoute: SetupTeamsRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  BracketRoute: BracketRoute,
  GameRoute: GameRoute,
  GkReportRoute: GkReportRoute,
  HomeRoute: HomeRoute,
  PlayersRoute: PlayersRouteWithChildren,
  QuartersRoute: QuartersRoute,
  ReportsRoute: ReportsRoute,
  ScoreboardRoute: ScoreboardRoute,
  SeasonRoute: SeasonRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
  StandingsRoute: StandingsRoute,
  StatsRoute: StatsRoute,
  UnlockRoute: UnlockRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
